services:
    get_book_list:
        class: App\GetBookList

    app:
        class: App\App
        arguments:
            - "@get_book_list"

    router:
        class: Symfony\Component\Routing
        arguments:
            -